### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] The compliance navigation section in the settings navbar is not completely visible on small screens

### ISSUE THREAD

**Issue by tarunclub** [formbricks/formbricks#1190] opened 2023-10-15 11:11 UTC
### Issue Summary

The compliance navigation section in the settings navbar is not completely visible on the desktop screen size.
<img width="583" alt="Screenshot 2023-10-15 161852" src="https://github.com/formbricks/formbricks/assets/102040059/471da4c5-c5c1-4bee-ae1c-a06c2ac2a83d">

### Steps to Reproduce

1. Go to settings
2. try to scroll the sidebar
3. you will see some part of the COMPLIANCE section is hidden

### Expected behavior

The compliance navigation should be visible on the full screen
<img width="577" alt="Screenshot 2023-10-15 163911" src="https://github.com/formbricks/formbricks/assets/102040059/22a4fe5f-7562-48e5-99d4-f80eecba73b0">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: 18.17.0
- npm: 9.6.7
```

**Comment by tarunclub** [comment] 2023-10-15 11:11
please assign this to me

**Comment by gauravp-dev** [comment] 2023-10-15 14:11
I would like to work on this issue. Please assign this to me.

**Comment by NilanjanPramanik** [comment] 2023-10-17 19:20
Can i work on it

**Comment by jobenjada** [comment] 2023-10-18 08:32
@gauravp-dev your next, we didnt get a solution from tarunclub :)

**Comment by ShubhamPalriwala** [comment] 2023-10-21 05:58
Hey @NilanjanPramanik, we're now assigning this to you since we did not get a PR from the previous assignee! 🤞🏼

**Comment by NilanjanPramanik** [comment] 2023-10-21 08:06
@ShubhamPalriwala  Hello sir I have found where the issue is but I stuck with a problem. Here I am referring some images
![Screenshot 2023-10-21 133008](https://github.com/formbricks/formbricks/assets/121485018/b9a9afca-b9b0-489e-a5ad-6e1b6eb4d24d)
When I clicked on "go to app" then I will be redirected to the hosted app
![Screenshot 2023-10-21 132956](https://github.com/formbricks/formbricks/assets/121485018/ad974610-8f64-46d5-be4b-db636442011e)

Please help me out if its possible..

**Comment by ratnaraj7** [comment] 2023-10-21 17:15
I would like to work on this issue.

**Comment by SumanKisku** [comment] 2023-10-23 03:47
I would like to work on this issue

**Closed** 2023-11-06 09:59 UTC
Labels: bug, hacktoberfest, formtribe-2023
