### ISSUE TITLE
[BUG] Download Responses Button text is not visible in UI.

### ISSUE THREAD

**Issue by shrikantpardhi** [formbricks/formbricks#1269] opened 2023-10-17 15:35 UTC
### Issue Summary

Once a survey is created. In the survey responses screen download response button text is not visible. 

### Steps to Reproduce

1. Create a Fake Door Follow-Up survey
2. Submit a survey
3. Open survey response

### Expected behavior

Download text should be visible in a button. 

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/26996069/a7a1f083-435b-4d72-9ad9-f2d789d57a75)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 10
- Node: >18
- Browser: Brave
```

**Comment by Dhruwang** [comment] 2023-10-17 15:42
Hey @shrikantpardhi ,
Thank you for checking out Formbricks 😊
But I am not able to reproduce this issue, can you recheck ?

**Comment by DarshanBorse** [comment] 2023-10-17 16:23
Kindly assign this task to me.

**Closed** 2023-10-18 08:45 UTC
Labels: bug
