### ISSUE TITLE
[BUG] EmailTab Breaks with Image Selection Question

### ISSUE THREAD

**Issue by KapadiaNaitik** [formbricks/formbricks#1511] opened 2023-10-30 08:19 UTC
### Issue Summary

 EmailTab Breaks with Image Selection Question

### Steps to Reproduce

1. Create new survey with image selection as first question
2. Publish Survey
3. Embed in Email

### Expected behavior

Email Tab should open

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by KapadiaNaitik** [comment] 2023-10-30 08:20
I would like to work on this

**Comment by gupta-piyush19** [comment] 2023-10-30 08:51
@Dhruwang This is the same issue as https://github.com/formbricks/formbricks/issues/1490
It's not breaking because of picture selection question, but because of the recent upgrade to next 14.
@neilchauhan2 is fixing the other one, that should close this too.

**Comment by jobenjada** [comment] 2023-10-30 09:09
@gupta-piyush19 did you build an email embed preview for the question select? :) I

**Comment by gupta-piyush19** [comment] 2023-10-30 09:17
Hey @jobenjada. Yes, I did. 🙂
I haven't added the default case for email template so that for every new question, it is mandatory to add the corresponding template, or else the build will fail.

**Comment by neilchauhan2** [comment] 2023-10-30 11:31
@jobenjada @gupta-piyush19 The email preview has been resolved now. @KapadiaNaitik could you please check if this issue has also been resolved with that fix. If yes, could you please close this. If not, could you please share a screen recording, showing how to reproduce this bug?

**Closed** 2023-10-30 11:57 UTC
Labels: bug
