### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Console Error

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1167] opened 2023-10-14 19:16 UTC
### Issue Summary

A component is changing from uncontrolled to controlled. This may be caused by the value changing from undefined to a defined value, which should not happen.

### Steps to Reproduce

1. go to https://formbricks.com/
2.  open console 

### Expected behavior

https://stackoverflow.com/questions/69690181/reactjs-warning-a-component-is-changing-an-uncontrolled-input-to-be-controll

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/84387676/fe7bcb62-b7c1-4cdf-9969-e06f136bfd17)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Microsoft edge, chrome
```

**Comment by mrkirthi-24** [comment] 2023-10-14 19:46
Hi @bilalmirza74 I would like to work on this issue.

**Comment by PankajKumarAgrawal1729** [comment] 2023-10-15 06:19
Hi @mrkirthi-24 @bilalmirza74 ,
can you please assign this issue for me

**Comment by jobenjada** [comment] 2023-10-15 08:55
@bilalmirza74 pls ship your fix today :)

**Comment by 3xp10it3r** [comment] 2023-10-15 18:24
I would like to work on this issue.

**Comment by ortin779** [comment] 2023-10-16 11:38
@jobenjada This is happening due to a state initialization. We initialized the initial value of `selectedState` in  `ThemeSelector`  as undefined. So whenever we change the value it is causing the issue.

Initialized the state with a `null` value, so that the error will be removed.
 
![Screenshot from 2023-10-16 17-08-12](https://github.com/formbricks/formbricks/assets/58628794/5a1062b1-b8f1-4f8c-afb9-42af3c30c504)


AFTER Fixing the issue: 

![Screenshot from 2023-10-16 17-07-42](https://github.com/formbricks/formbricks/assets/58628794/f711e2c9-b156-48f3-bf66-20777fe08a44)

**Comment by ortin779** [comment] 2023-10-16 11:51
@bilalmirza74  Raising a PR shortly, Just finishing up the checks

**Comment by ortin779** [comment] 2023-10-16 11:56
@bilalmirza74 @jobenjada created the PR https://github.com/formbricks/formbricks/pull/1220, Please review it.

**Comment by ShubhamPalriwala** [comment] 2023-10-17 07:02
Hey @ortin779, I still see the following bug on formbricks.com landing page:
![Screenshot_2023-10-17-12-31-40_5760x1080](https://github.com/formbricks/formbricks/assets/55556994/ef72882a-ebbd-49cc-9753-f4981fe2a856)

What's the status with this?

**Comment by ortin779** [comment] 2023-10-17 07:28
> Hey @ortin779, I still see the following bug on formbricks.com landing page:
> ![Screenshot_2023-10-17-12-31-40_5760x1080](https://github.com/formbricks/formbricks/assets/55556994/ef72882a-ebbd-49cc-9753-f4981fe2a856)
> 
> What's the status with this?

@ShubhamPalriwala looks strange to me, I am actually out of town. Will look once I am back.

Meanwhile can you check these changes are deployed to Prod or not!

**Comment by ShubhamPalriwala** [comment] 2023-10-17 07:39
Yeah, cannot reproduce this on local! Will revert if witnessed again on prod once we fix the build pipeline! Closing this as complete for now

**Closed by ShubhamPalriwala** 2023-10-17 07:39 UTC
Labels: bug, hacktoberfest, formtribe-2023

**Comment by ortin779** [comment] 2023-10-18 05:56
@ShubhamPalriwala Hey verified on the latest deployment, it is working.
![Screenshot_2023-10-18-11-25-11-609_com.android.chrome.jpg](https://github.com/formbricks/formbricks/assets/58628794/8b2da8c7-e6e7-4d6d-aa60-02a0596d9884)
