### ISSUE TITLE
[BUG] Free text editor in CTA and Consent questions break Survey Editor

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1212] opened 2023-10-16 10:01 UTC
### Issue Summary

<img width="1425" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/3728e969-c987-4766-a9d8-9ab3085af895">

The reason might be the HTML Editor causing the same error, because the app breaks for question type CTA and Consent:

<img width="1435" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/67e5cb27-d371-4b18-8fd9-3d63b8960699">

<img width="1438" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/6bf9e27b-4919-437f-aaad-788eac1b3317">

### Steps to Reproduce

1. Go to cloud app
2. Create survey with PMF Superhuman template
3. Or an empty survey and add CTA question

### Expected behavior

Dont break :)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by gupta-piyush19** [comment] 2023-10-16 10:02
Hey! Would love to pick this up.

**Comment by 3xp10it3r** [comment] 2023-10-16 10:24
Would Like to work on this.

**Comment by jobenjada** [comment] 2023-10-16 11:17
@gupta-piyush19 you were first, have a shot at it :)

**Comment by gupta-piyush19** [comment] 2023-10-17 11:37
@jobenjada Seems like it's fixed with some other change; you can now close it.

**Comment by KapadiaNaitik** [comment] 2023-10-17 11:48
@gupta-piyush19 I think this was mostly related to text duplication in ToolbarsPlugin. I modified it while working on WelcomeCard so I guess this got fixed with it. So sorry to cause redundant work 😅

**Comment by gupta-piyush19** [comment] 2023-10-17 11:54
Yeah right! Thanks for fixing it. @KapadiaNaitik 🚀

**Comment by ShubhamPalriwala** [comment] 2023-10-17 12:39
Tried to reproduce this with @Dhruwang but we tested all the possible cases! Looks like this is fixed haha, closing this 🚀 🤞🏼

**Closed by ShubhamPalriwala** 2023-10-17 12:39 UTC
Labels: bug
