### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Duplicate Survey not working

### ISSUE THREAD

**Issue by edersilva78** [formbricks/formbricks#1222] opened 2023-10-16 12:21 UTC
### Issue Summary

When duplicating a survey, you get the message the process was done, but in fact, no new survey is created
![image](https://github.com/formbricks/formbricks/assets/7780778/2f19e31f-37b2-4eb9-a711-dec89a2f3255)

No logs on server.

### Steps to Reproduce

1. 
![image](https://github.com/formbricks/formbricks/assets/7780778/acdb7f60-2770-4b19-8826-ceaac4753810)

2. 
![image](https://github.com/formbricks/formbricks/assets/7780778/0f28887c-d68e-4a25-ba49-f32fb08d004c)

3. no survey is created.
4. Refresh page or new login confirms the issue

### Expected behavior

a new survey would be created, a copy of the selected survey.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
FB Version: 1.1
Self-hosted docker container
```

**Comment by jobenjada** [comment] 2023-10-16 12:27
@edersilva78 thanks a lot for letting us know, looking into it asap :)

**Comment by Ujjwal55** [comment] 2023-10-16 12:49
I want to pick this up

**Comment by edersilva78** [comment] 2023-10-16 13:03
update: now I have 10+ copies of the survey. 
the site was responsive at the time, so was the server.

**Comment by edersilva78** [comment] 2023-10-16 13:07
![image](https://github.com/formbricks/formbricks/assets/7780778/f1a49a4e-d68b-4503-bb66-5e38d488cda2)

**Comment by ortin779** [comment] 2023-10-16 13:11
@edersilva78 it is creating duplicates, but router.refresh() is not invalidating the cache
Which is why we are getting the previous surveys only. you can try refreshing `ctrl + shift + R` or `cmd+shift+r`, you will see the duplicated ones

@bilalmirza74 are you looking into this??

**Comment by ortin779** [comment] 2023-10-16 13:32
Got the root cause of the issue @bilalmirza74. If you want i can pair with you!

**Comment by ortin779** [comment] 2023-10-16 13:40
Sure, Shall we connect??

**Comment by ortin779** [comment] 2023-10-16 13:41
Let me ping you the google meet link!!

**Comment by ortin779** [comment] 2023-10-16 13:42
@bilalmirza74 https://meet.google.com/sji-ppiq-thv please join this link

**Comment by ShubhamPalriwala** [comment] 2023-10-17 09:28
Closed via #1229

**Closed by ShubhamPalriwala** 2023-10-17 09:28 UTC
Labels: bug, hacktoberfest, formtribe-2023
