### ISSUE TITLE
[BUG] Pricing Free/Paid box needs to be centered.

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1371] opened 2023-10-21 04:36 UTC
### Issue Summary

This needs to be centered aligned.

<img width="950" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/e432e1f6-b092-4a12-ae06-9d0d79dfa046">

Smaller Screen 

<img width="235" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/654f2a7b-3327-4084-b27d-4965981daadb">

### Steps to Reproduce

Navigate to pricing section from navbar.

URL : https://formbricks.com/pricing

### Expected behavior

This looks more good

<img width="947" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/33743ae6-c867-4b65-8ee4-cffd6941165a">

Smaller Screen 

<img width="293" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/5430b34c-c7c9-4078-bb47-c8f0b391a782">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Not required
- Node: Not required
- npm: Not required
```

**Comment by itzabhinavarya** [comment] 2023-10-21 04:37
@jobenjada @ShubhamPalriwala Sir, If this needs to be fixed then let me know, i will open a PR for the same. or If this will be as it is same then kindly close the Issue, with remark. 
Thanks

**Comment by ShubhamPalriwala** [comment] 2023-10-22 13:44
Hey @itzabhinavarya, this is not a Bug. If you observe, the table has rows below each column of Free and Paid hence why it's intentionally not centered! Making the table headings centered really messes up the UX of the page and makes it confusing to understand the difference between the plans. 

Hence closing this bug and subsequent PRs! Hope you agree with the same as well 💯

**Closed by ShubhamPalriwala** 2023-10-22 13:44 UTC
Labels: bug

**Comment by myselfprincee** [comment] 2023-10-22 13:51
I saw an issue regarding this, that is why I made a PR. By the way, Thanks 👍

**Comment by itzabhinavarya** [comment] 2023-10-22 14:12
@ShubhamPalriwala I thought about the same while generating the issue, that' why I said to Close the issue with remark if it is all good.
BTW thanks :) 

@ShubhamPalriwala Kindly look at my another PR. :)
