### ISSUE TITLE
[BUG] Login/Create account is broken on website

### ISSUE THREAD

**Issue by Motoxpro** [formbricks/formbricks#1726] opened 2023-12-03 23:21 UTC
### Issue Summary

If you try to create an account with google it kicks you back to the login page.

If you try to create an account with email, and then you verify your email, it leaves you with a 500 error

### Steps to Reproduce

1. Try to create a new account

### Expected behavior

That you can create an account.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac
- Browser: Chrome
```

**Comment by pandeymangg** [comment] 2023-12-04 16:32
Hey @Motoxpro 
Thank you for reporting this issue. I've attempted to reproduce the issue following the steps you described, but I haven't been able to replicate the behavior on my end. Could you perhaps share more details like a screenshot or a video of the the bug? That would be helpful.

Thanks 🙂

**Comment by tvankith** [comment] 2023-12-05 07:05
@pandeymangg I got page with 500 in my first testing. When i tested login second time for taking video, error changed to "A user with this email exists already."
- OS: Ubuntu
- Browser: Chrome
- Environment: Cloud

https://github.com/formbricks/formbricks/assets/22615249/52d81b07-7dff-4d83-b7f8-c1791235f418

**Comment by tvankith** [comment] 2023-12-05 08:59
> @pandeymangg I got page with 500 in my first testing. When i tested login second time for taking video, error changed to "A user with this email exists already."
> 
> * OS: Ubuntu
> * Browser: Chrome
> * Environment: Cloud
> 
>  vokoscreenNG-2023-12-05_12-30-33.mp4

I successfully logged in using my GitHub account. However, I received an error message stating, "A user with this email already exists." It seems that despite being redirected to a 500-page error, my account was created using GitHub credentials.

**Comment by mattinannt** [comment] 2023-12-05 15:46
@tvankith Did you manage to create a Formbricks account?
We found two minor problems in the login flow and fixed them. However, we have not been able to directly reproduce the Google login issue.

**Comment by mattinannt** [comment] 2023-12-08 14:00
Unfortunately, I was not able to reproduce the problem, but one of our developers will look into it further.

**Comment by pandeymangg** [comment] 2023-12-14 11:52
I've tested the login functionality with multiple google accounts and emails as well, but couldn't reproduce the same problem 😞

**Comment by mattinannt** [comment] 2023-12-14 12:06
Closing this issue for now as we currently have no way to reproduce it.

**Closed by mattinannt** 2023-12-14 12:06 UTC
Labels: bug
