### ISSUE TITLE
[BUG] Login with google redirects to incorrect URL

### ISSUE THREAD

**Issue by Aaryansh1** [formbricks/formbricks#2797] opened 2024-06-21 12:18 UTC
### Issue Summary

Tried to login with google redirected back to this URL https://app.formbricks.comhttps/app.formbricks.com/

### Steps to Reproduce

1. Went to https://formbricks.com/ and get started
2. Log in using google
3. After login got redirected back to https://app.formbricks.comhttps/app.formbricks.com/

### Expected behavior

It should redirect back to https://app.formbricks.com/

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Brave
```

**Comment by STAR-173** [comment] 2024-06-24 11:36
I was trying to recreate this issue but was unable to do so.
The login is working just as intended.

`- OS: Windows`
`- Browser: Chrome`

**Comment by Aaryansh1** [comment] 2024-06-24 11:48
@STAR-173 I also just re-tried, It's working now. but I am also facing the issue you mentioned. It could also be an issue where user is trying to login using an unregistered account. It needs more testing.

**Comment by STAR-173** [comment] 2024-06-24 12:04
Btw guess what, I just retried it with my phone and I got the initial invalid link you mentioned. 
Tried it one more time and everything worked just fine.

Seems like an RNG in the background deciding our fate to login 😂

**Comment by Dhruwang** [comment] 2024-08-07 10:16
Unfortunately was not able to reproduce it. Closing it for now 😊

**Closed by Dhruwang** 2024-08-07 10:16 UTC
Labels: bug
