### ISSUE TITLE
[BUG] On landing page second banner color is white in dark mode.

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1429] opened 2023-10-23 14:15 UTC
### Issue Summary

In dark mode the banner is showing white and in light mode it is showing dark. 

Reference : 
<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/ac75aa97-5e6c-403b-a858-db7cc4a491b7">

### Steps to Reproduce

1. Landing page
2. Second banner. same as on the issue section

### Expected behavior

<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/223d45e9-4ae0-4eac-b9ef-f53fff178cb3">

<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/815e9ee7-97b0-4f64-a134-766faa455772">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Not required
- Node:Not required
- npm: Not required
```

**Comment by itzabhinavarya** [comment] 2023-10-23 14:16
@jobenjada @ShubhamPalriwala Please assign this to me.

**Comment by PentesterPriyanshu** [comment] 2023-10-23 19:22
please assign this to me i am doing this

**Comment by itzabhinavarya** [comment] 2023-10-23 19:24
Hi @PentesterPriyanshu , I already have opened a PR for the same. Kindly look on another issues or bugs, it's better to find it by yourself. Do read the Contributing Guidelines for this Repo. 
Thanks:)

**Comment by PentesterPriyanshu** [comment] 2023-10-23 19:38
ok

**Comment by ShubhamPalriwala** [comment] 2023-10-25 03:11
Hey @itzabhinavarya, thanks for opening an issue! But the color schemes are intentionally inverted hence this is not a bug as such! Appreciate your time and efforts on this, would recommend to get inside the app and see if you can catch some bugs there 🐛 

Closing this as well as the PR associated!

**Closed by ShubhamPalriwala** 2023-10-25 03:11 UTC
Labels: bug

**Comment by itzabhinavarya** [comment] 2023-10-25 03:37
@ShubhamPalriwala Ok Sir, Thanks
