### ISSUE TITLE
Allow team invites when public signup is disabled

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#250] opened 2023-04-25 09:17 UTC
At the moment you can set the environment variable  `NEXT_PUBLIC_SIGNUP_DISABLED=1` to disable the public signup. Unfortunately this also breaks the team invite functionality as users can't register after receiving an invite link via email.

To solve this add a new environment variable `NEXT_PUBLIC_INVITE_DISABLED=1` that explicitly disables the invite functionality together with the signup for invites.
And change the default behaviour that if `NEXT_PUBLIC_SIGNUP_DISABLED=1` signup for invites is still allowed.

**Comment by niteshseram** [comment] 2023-06-13 14:07
Hi, @mattinannt Can I pick this up?

**Comment by mattinannt** [comment] 2023-06-14 11:28
@niteshseram Sure, great that you want to support 💪 I have assigned the issue to you. If you have any questions feel free to contact me. Can you give an estimate when you think you have a first version ready?

**Comment by niteshseram** [comment] 2023-06-14 13:52
Hi, @mattinannt Thanks for assigning it to me. It shouldn't take much time here. But right now, I got stuck on one issue while working on this. The issue is whenever I log in I see the below screen. Right now, I am trying to debug why this is happening. Have you encountered anything like this locally?


![image](https://github.com/formbricks/formbricks/assets/51370246/cac7ccaf-08a3-4c55-aac2-b6f57c131db3)

**Comment by mattinannt** [comment] 2023-06-15 07:06
@niteshseram Can you see a more specific error in the browser logs (right click -> inspect -> console) or in the server logs (your server running in the terminal or VS-Code)?

**Comment by niteshseram** [comment] 2023-06-15 14:23
@mattinannt Something is happening around this function https://github.com/formbricks/formbricks/blob/00acdf58f17b4394e386e9a62db4992a7e8dde01/apps/web/app/page.tsx#L8

Could see this error in the console 
![image](https://github.com/formbricks/formbricks/assets/51370246/69be18da-1134-4b2b-917f-6c98b1a37daa)

**Closed** 2023-06-21 09:53 UTC
Labels: enhancement, help wanted
