### ISSUE TITLE
[BUG] Email Preview causing error

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1490] opened 2023-10-28 15:43 UTC
### Issue Summary

I'm getting an error when trying to access the Email Preview:

https://tella.video/johanness-video-65ku

### Steps to Reproduce

1. Create a link survey
2. Click on the Embed in Email tab

### Expected behavior

Should open the email preview tab :)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by raghavnagar7** [comment] 2023-10-29 19:24
It appears that you're experiencing an issue with Formbricks when trying to access the Email Preview. To address this issue, you can follow these steps:

**1. Confirm the Issue:**
   - Ensure that the issue persists and is not due to a temporary glitch or connectivity problem.

**2. Check for Browser Compatibility:**
   - Ensure that your browser is supported for accessing the Email Preview feature in Formbricks. It's recommended to use the latest versions of popular browsers like Chrome, Firefox, or Edge.

**3. Clear Cache and Cookies:**
   - Sometimes, browser cache and cookies can cause unexpected issues. Try clearing your browser's cache and cookies, and then attempt to access the Email Preview again.

**4. Disable Browser Extensions:**
   - Some browser extensions or add-ons can interfere with web applications. Temporarily disable any extensions that may be causing conflicts and test the Email Preview again.

**5. Browser Version:**
   - Make sure you're using an up-to-date version of your browser.

**6. Network Connection:**
   - Ensure that you have a stable internet connection, as network issues can disrupt the loading of web content.

**7. Contact Formbricks Support:**
   - If the issue persists and seems to be related to Formbricks, contact their support team. Provide them with details about the error you're encountering, the steps to reproduce it, and the URL you shared.

**8. Node and npm Versions (if Self-hosted):**
   - If you're using a self-hosted version of Formbricks, ensure that you have the correct versions of Node.js and npm installed. Formbricks may have specific requirements, so double-check their documentation.

To get a more precise solution or explanation of the error, it's essential to reach out to Formbricks support. They can help you identify the cause of the issue and provide guidance on how to resolve it. The information you provide, such as the URL and details about the error, will be helpful for their support team to assist you effectively.

**Comment by neilchauhan2** [comment] 2023-10-30 08:41
@Dhruwang I'm taking this up

**Comment by neilchauhan2** [comment] 2023-10-30 11:29
Closing this, since this has been resolved.

**Closed by neilchauhan2** 2023-10-30 11:29 UTC
Labels: bug
