### ISSUE TITLE
[BUG][FormTribe 🔥][200 Points] Error on setting userId with the method setUserId

### ISSUE THREAD

**Issue by EduardoNoronha31** [formbricks/formbricks#1135] opened 2023-10-13 17:02 UTC
### Issue Summary

When I set userId using the setUserId method this error appears and I can't proceed with the form. 

I tried to reset the users but the problem still happened.

### Steps to Reproduce

1. Follow the documentation using [Vue.js](https://formbricks.com/docs/getting-started/framework-guides#vue-js)
2. Set some userId with the setUserId method
3. Click on the next button and check the console

### Expected behavior

I expected the normal navigation with a set userId in Formbricks data.

### Other information

Removing the following line, the form works well.

![image](https://github.com/formbricks/formbricks/assets/78568517/d94965e9-38e5-4f90-b1b9-bd05a905d2a8)

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/78568517/9ae9ef40-707e-4787-96b5-3447af0d9d11)
![image](https://github.com/formbricks/formbricks/assets/78568517/c5ac48af-8eff-4f87-ab52-8e2c51ff8fef)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux Ubuntu
- Node: 16.17.0
- npm: 8.15.0
- Browser: Google Chrome - Version 117.0.5938.132 (Official Build) (64-bit)
- @formbricks/js: 1.0.7
```

**Comment by mattinannt** [comment] 2023-10-13 18:36
@EduardoNoronha31 Can you please share the logs of your self-hosted Formbricks. Internal server error suggests that the server is logging the error message with the cause

**Comment by vishalkhoje** [comment] 2023-10-14 11:06
I am interested to work on this issue can you please assign this issue to me.

**Comment by jobenjada** [comment] 2023-10-14 15:51
@vishalkhoje its your, you'll be awared 200 points for a solid fix :)

**Comment by vishalkhoje** [comment] 2023-10-14 20:18
Hi @EduardoNoronha31 
Can you please write a detailed description steps to reproduce the issue with a step-by-step with video?

Also please share the logs of your self-hosted Formbricks. Internal server error suggests that the server is logging the error message with the cause.

Where i will be able to find this file code (setUserId)?
![image](https://github.com/formbricks/formbricks/assets/36984676/27b8932a-beeb-4155-91be-bc28d7bb1317)

I tried with vue sample app it's working as expected, not getting any error.

**Comment by vishalkhoje** [comment] 2023-10-16 13:48
Hi @EduardoNoronha31 ,
Can you please share the more details

**Comment by EduardoNoronha31** [comment] 2023-10-16 16:54
Hi @vishalkhoje, I'm sorry for don't answer earlier. Here is all the configuration about Formbricks in my project.

I'm using the Quasar framework with Vue.js 3.
![image](https://github.com/formbricks/formbricks/assets/78568517/96e9e741-316d-4136-a52e-f81dcc10ca99)

The boot files of Quasar provide an instance of the Vue.js app, then, I configured the Formbrics globally:
![image](https://github.com/formbricks/formbricks/assets/78568517/4f268052-2a42-4001-a0ab-9583f919c4f3)

Finally, I made a request to get the user data and set the attributes with the global instance of Formbricks on the home page.
![image](https://github.com/formbricks/formbricks/assets/78568517/d1b6c569-548e-4fe7-b861-fbfd8c38d332)

**Comment by vishalkhoje** [comment] 2023-10-16 17:39
Hi @EduardoNoronha31 
No worries, and thank you for the response. Are you now able to make requests with attributes? Has your issue been resolved?

Please let me know if you have any further questions or concerns.

**Comment by EduardoNoronha31** [comment] 2023-10-16 18:23
Yes, I can make requests using the setAttribute method, but when I use the setUserId method, errors appear in the console and I can't proceed with the form. @vishalkhoje

**Comment by mattinannt** [comment] 2023-10-17 12:37
@EduardoNoronha31 The `500 internal server error` message indicates that this error is not thrown in the vue app, but on the formbricks server ( forms.institutomix.com ).
Please share the logs from this instance and also the Formbricks version number you are running on the server.

**Comment by EduardoNoronha31** [comment] 2023-10-17 16:19
@mattinannt @vishalkhoje 
I asked the person responsible for implementing the Formbricks server at the company I work for and he said that there are not any different logs than Vue.js logs.

Formbricks version is: 1.1.0

**Comment by mattinannt** [comment] 2023-10-17 17:43
@EduardoNoronha31 thanks for clarifying. Unfortunately that doesn't give us much information about what's going on.
We already fixed a lot of errors in the last few weeks. The best approach I can think of right now is updating Formbricks. The latest version available is 1.1.2 and version 1.2 will be released soon.
But If it's not making too much trouble I would suggest updating to formbricks 1.1.2 first. As there are no breaking changes during patch releases it should be an easy update.

**Comment by EduardoNoronha31** [comment] 2023-10-17 18:14
Okay, I'll request the update, and if it doesn't work I'll be back here and report again. Thank you for your attention @mattinannt

**Comment by ShubhamPalriwala** [comment] 2023-10-21 05:30
Hey @EduardoNoronha31, the docker image is for our web interface app!

For the integration, you'd be using the `formbricks/js` package right, so for that we suggested to bump up the version and test it again. 

Please do the above and let us know if you are still facing the issue.

**Comment by EduardoNoronha31** [comment] 2023-10-23 17:10
I bumped up the formbricks/js version to 1.1.3 (the last version) and a new error appeared in the console.

![image](https://github.com/formbricks/formbricks/assets/78568517/7e447aba-dfe6-45a9-9a0e-136baab7ecce)

![image](https://github.com/formbricks/formbricks/assets/78568517/7dcb13a1-93de-41d6-8cb0-ff7e7e582da0)

@ShubhamPalriwala

**Comment by mattinannt** [comment] 2023-11-14 07:27
We updated a lot of code in formbricks-js during the last few weeks and tried so solve as many issues as possible with the new user identification strategy
https://formbricks.com/docs/attributes/identify-users

I'm closing this for now. If the error persists with the new version in some way, we will open this again 😊

**Closed by mattinannt** 2023-11-14 07:27 UTC
Labels: bug, hacktoberfest, formtribe-2023
