### ISSUE TITLE
[FormTribe 🔥][1000 Points] Validation for Number, URL, Email and Phone Number in Open Text Question

### ISSUE THREAD

**Issue by Dhruwang** [formbricks/formbricks#909] opened 2023-10-02 12:08 UTC
### Welcome to the FormTribe

This issue will get you **1000 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

### Is your feature request related to a problem? Please describe.

The free text field is often used for general details such as Email, Phone number, Integer, etc. Survey responses having incorrect data type makes it difficult for survey creators to parse it in a generalised and bulk way.

### Describe the solution you'd like

The survey should pack validation at the client side itself ie when a user is submitting a survey to make it more versatile and assure that the data which is put in, is actually the data the survey creator expects.

### Tasks

We primarily have 2 sides to tackle:

1. For the admin side: We have to give them an option to toggle between what they want the specific validation to be (Number, URL, Email, Phone Number) in the survey creation/editing part.
2. For the user side: Validate if the user gets appropriate error/warning if they do not pass valid information.

We will follow a top-down approach for easier understanding and slowly diving into the core engineering.

### Admin Side:

1. In the Survey JS package, you will find the OpenTextQuestion file: [https://github.com/formbricks/formbricks/blob/main/packages/surveys/src/components/OpenTextQuestion.tsx](https://github.com/formbricks/formbricks/blob/e0b04a75a4abc9fafe4b4ca6be8a94aacce58170/packages/surveys/src/components/OpenTextQuestion.tsx)
2. We now need to build a reusable multi toggle component for the question types, try to use ShadCN and add a component for faster turnaround time and uniformity across the app.
3. Add a component inside it where the survey creator can set the question type as below.
<img width="962" alt="image" src="https://github.com/formbricks/formbricks/assets/67850763/20229097-56ce-4841-a9db-3196fdf6477b">

4. Make sure the default is set to normal open text question type
5. Once the UI is done and you are able to parse the input type the survey admin selects, we will now shift our focus to how do we make this work.
6. The next question should be, where/how do we store this input type, for which we will now go to our schema in the database and see whats the cleanest way of adding an option.
7. In this file (https://github.com/formbricks/formbricks/blob/e0b04a75a4abc9fafe4b4ca6be8a94aacce58170/packages/types/v1/surveys.ts), you will find the ZSurveyOpenTextQuestion type that we use for the Open Question. Now, add a field in here that will hold the type, name it "inputType" with possible values "text" | "email" | "url | "number" | "phone".
8. To maintain Backward Compatibility (ie to make sure the previous opentext questions do not break since we are adding a new field), keep in mind to keep the field optional and during parsing at the client side, remember to track the case of the field not existing and treat is a normal open text question.
9. Now that we have the database supporting us with a new field, we will follow the story mode (ie how this feature will come live).
10. First, the survey admin will visit the survey editor to create a survey with such a question type, so go to this file ([https://github.com/formbricks/formbricks/blob/main/apps/web/app/(app)/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/edit/SurveyEditor.tsx](https://github.com/formbricks/formbricks/blob/e0b04a75a4abc9fafe4b4ca6be8a94aacce58170/apps/web/app/(app)/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/edit/SurveyEditor.tsx)) and slowly navigate your way deeper with where you need to make the change to add the new type when a new survey is created or an old one is edited.
11. Once this is done and you can see the inputType coming in your database, you have the admin side ready!

### User Side

1. Now thinking from the perspective of a user when they see a survey, the same component is called here ([https://github.com/formbricks/formbricks/blob/main/packages/surveys/src/components/OpenTextQuestion.tsx](https://github.com/formbricks/formbricks/blob/0a08d7df680dde5aceef9ac6e86410a4d5de5c05/packages/surveys/src/components/OpenTextQuestion.tsx)), we need to validate based on the input type and set it accordingly. Look into how you can do simple validation based on the input value and the input type. 
2. Please do not install an additional library for validation. We do not require anything complex. For example, for phone numbers, we should only allow the "+" field and only numbers. Please make it work with JS validations and the HTML native tags if they exist.

### Thanks!

**Comment by ykburda** [comment] 2023-10-02 14:09
where is date?

**Comment by ashishk1331** [comment] 2023-10-02 17:56
Okay! This is the big fish issue.
And there are sides to it,
1. Server side: Coretta data schema addition to the database.
2. Admin side: UI update to select correct type which corresponds to right validation schema to chose at client side.
3. Client side: I guess simple regex edge testing can help resolve issues.

If you think I get the gist right, then I would love to work on implementing the same.

**Comment by jobenjada** [comment] 2023-10-03 04:44
⚠️ We have a promising PR up from @KapadiaNaitik and will work with them to get it merged. Will post here in case we're opening this up for more contributions ⚠️

**Comment by ashishk1331** [comment] 2023-10-03 05:16
Okay.

**Comment by Rajarshi-Misra** [comment] 2023-10-04 13:40
Hi
If the issue is still open, please let me work on it. Thank you

**Comment by manpoffc** [comment] 2023-10-05 03:26
Hello is this issue still open?

**Comment by ykburda** [comment] 2023-10-06 19:38
Hi,
Wouldn’t be an option for date? Or will it be question type later?

**Closed** 2023-10-08 09:32 UTC
Labels: enhancement, hacktoberfest, formtribe-2023
