### ISSUE TITLE
[BUG] Filters not applying to Detailed Survey Answers in Responses Tab

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1938] opened 2024-01-22 13:24 UTC
### Issue Summary

I observed that the filters are not functioning as expected for detailed survey answers. They appear to only take effect when navigating from the summary tab.

### Steps to Reproduce

1. Create a survey with an open-text field question (this issue might extend to other question types, though untested).
2. Collect responses to the survey.
3. Navigate to the "Responses" tab.
4. Attempt to apply filters.
5. Observe that the filters do not take effect as intended.
6. When applying the filters on the Summary tab and then switching to Responses it does work.

### Expected behavior

Filters should consistently apply to survey answers, irrespective of the current tab.

### Other information

*No response*

### Screenshots

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/cf5fb02e-f397-4c7b-8a11-205e7fcf3563/30621de8-b646-4b49-aafa-db61982fa067?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC9jZjVmYjAyZS1mMzk3LTRjN2ItOGExMS0yMDVlN2ZjZjM1NjMvMzA2MjFkZTgtYjY0Ni00YjQ5LWFhZmEtZGI2MTk4MmZhMDY3IiwiaWF0IjoxNzA5ODgzMTY5LCJleHAiOjMzMjgwNDQzMTY5fQ.Nlzv_mYYcGOTxsopXWExVexioeCIRyuFCzI6B1rrdgA)

The first response should not be visible since the question is skipped.

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/6e37b777-fa06-464f-aeef-f900ad356d80/ab9c17d7-696b-41b4-89e3-320f0e9e2acf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC82ZTM3Yjc3Ny1mYTA2LTQ2NGYtYWVlZi1mOTAwYWQzNTZkODAvYWI5YzE3ZDctNjk2Yi00MWI0LTg5ZTMtMzIwZjBlOWUyYWNmIiwiaWF0IjoxNzA5ODgzMTY5LCJleHAiOjMzMjgwNDQzMTY5fQ.-grLeL-J374fT4H3h82FnqKfeUvOtaTryvEq2wWBWLk)

The first response should not be visible since the user answered Question 1.

(btw: the issue is not resolved by closing the filter modal)

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```
- Browser: Chrome 120
```

**Comment by mattinannt** [comment] 2024-01-22 13:28
@jonas-hoebenreich thanks for reporting this issue 😊 We are already working on a solution for this.
We are currently restructuring the summary and responses view to scale better with large numbers of responses and to load the responses paginated, including moving the filters to the server side.

**Comment by MaxWohlers** [comment] 2024-03-06 18:04
@mattinannt Not sure if similar and if this bug will be fixed with your proposed solution, but I realized today that in the summary when setting a certain time frame the **Displays** do not adjust to the time frame, but Starts, Responses, Drop Offs, Time to Complete do change with the timeframe, resulting in inaccurate summary calculations. 
Let me know if I should create a separate ticket or if this will be resolved with your fix as well. 
<img width="846" alt="Bildschirmfoto 2024-03-06 um 19 02 27" src="https://github.com/formbricks/formbricks/assets/37698250/a743566a-687b-490b-8b1a-80e0ca4ed758">
<img width="840" alt="Bildschirmfoto 2024-03-06 um 19 02 15" src="https://github.com/formbricks/formbricks/assets/37698250/e4ee7281-8c75-40ba-9fc3-b833e8bfdb84">
<img width="853" alt="Bildschirmfoto 2024-03-06 um 19 01 42" src="https://github.com/formbricks/formbricks/assets/37698250/f111e11b-04a5-4085-86c9-de360bc5676f">

**Comment by mattinannt** [comment] 2024-03-08 07:36
@jonas-hoebenreich The issue is now fixed with the new survey server-side summary in https://github.com/formbricks/formbricks/pull/2160

@MaxWohlers Let us investigate this issue and come up with a solution. @gupta-piyush19 Can you please take a look? 😊

**Comment by mattinannt** [comment] 2024-04-11 14:25
fixed in #2208 😊

**Closed by mattinannt** 2024-04-11 14:25 UTC
Labels: bug
