### ISSUE TITLE
[BUG] Button's loading spinner overlaps the text

### ISSUE THREAD

**Issue by sitek94** [formbricks/formbricks#966] opened 2023-10-05 20:26 UTC
### Issue Summary

When loading spinner is shown in button it overlaps the button's text:

https://github.com/formbricks/formbricks/assets/58401630/e0aff2e3-7e38-4017-8066-00e8eb530c64

### Steps to Reproduce

1. Went to [settings/lookandfeel](https://app.formbricks.com/environments/clnd9b5b22wb4nt0fgrezg21k/settings/lookandfeel)
2. Clicked on "Save" button

### Expected behavior

For better UX, I'd expect that the loading spinner either replaces the text or is shown next to it, like for example in MaterialUI:

https://github.com/formbricks/formbricks/assets/58401630/aae282cb-f222-4cd3-a651-2d85c4d46496

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
N/A
```

**Comment by mattinannt** [comment] 2023-10-05 20:36
@sitek94 Thanks a lot for the feedback. 💪🙏
This is actually expected behaviour for now and not a bug. We understand that this might be confusing and we forwarded your feedback to our design team which is currently preparing a redesign of Formbricks :-)  💪
But since this is not a bug that needs to be fixed urgently, I'm closing this issue for now.

**Closed by mattinannt** 2023-10-05 20:36 UTC
Labels: bug
