### ISSUE TITLE
Calling track function shows blank screen.

### ISSUE THREAD

**Issue by Sarmadkhalid1** [formbricks/formbricks#4399] opened 2024-12-04 13:24 UTC
### Issue Summary

I was using Formbricks but suddenly it is not working anymore in my React native mobile app 

 LOG  🧱 Formbricks - 2024-12-04T12:13:48.191Z [DEBUG] - Formbricks: Action "Button Clicked" tracked
 ERROR  TypeError: Cannot read property 'styling' of undefined

    "@formbricks/react-native": "^1.1.0",
    "react-native-webview": "^13.12.3",
    "react-native": "0.73.7",

This error is located at:
    in ia
    in Unknown (created by App)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in ThemeProvider (created by App)
    in _QueryClientProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in EMTeam(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'styling' of undefined

### Your Environment

None

**Comment by mattinannt** [comment] 2024-12-04 14:38
Thanks for reporting. @pandeymangg Can you please take a look and try to reproduce the issue?

**Comment by CesarNobre** [comment] 2024-12-04 14:38
Hello!

Same error here: 

```
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - Custom error handler: no
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - Start initialize
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - No existing configuration found.
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - No valid configuration found or it has been expired. Creating new config.
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - Syncing.
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - No cache option set for sync
 LOG  🧱 Formbricks - 2024-12-04T14:34:07.240Z [DEBUG] - syncing with backend
 LOG  🧱 Formbricks - 2024-12-04T14:34:08.075Z [DEBUG] - Fetched 1 surveys during sync: Cart Abandonment Survey
 LOG  🧱 Formbricks - 2024-12-04T14:34:08.076Z [DEBUG] - Formbricks: Action "New Session" tracked
 ERROR  TypeError: Cannot read property 'styling' of undefined
 LOG  🧱 Formbricks - 2024-12-04T14:34:08.097Z [DEBUG] - Initialized
```

`"react-native": "0.74.5",`

**Comment by pandeymangg** [comment] 2024-12-05 06:28
hey @CesarNobre @Sarmadkhalid1 we recently changed the naming of products to projects, it seems to me that the error is related to that, although I couldn't  reproduce it in my testing and it worked fine. Could you also share your `environmentId` as well? I can check on prod what's going wrong 🙏

**Comment by Sarmadkhalid1** [comment] 2024-12-05 08:41
@pandeymangg 

environmentId: 'cm379f20a0007ob5x8ws1zkue'

**Comment by CesarNobre** [comment] 2024-12-05 14:00
@pandeymangg envId: cm46fe12q0007lu00g165xvr4

Thank you!

**Comment by pandeymangg** [comment] 2024-12-05 14:52
hey! @Sarmadkhalid1 @CesarNobre Thanks for raising the issue, I was able to debug it. We changed our api types a bit but we still haven't released a new version of `@formbricks/react-native` which is why it errors out since it looks for the older types. We'll likely publish an updated version of the package tomorrow on npm, this will be fixed with it 😊

**Comment by pandeymangg** [comment] 2024-12-06 14:01
> hey! [@Sarmadkhalid1](https://github.com/Sarmadkhalid1) [@CesarNobre](https://github.com/CesarNobre) Thanks for raising the issue, I was able to debug it. We changed our api types a bit but we still haven't released a new version of `@formbricks/react-native` which is why it errors out since it still references the older types. We'll likely publish an updated version of the package tomorrow on npm, this will be fixed with it 😊

we just released the new version of `@formbricks/react-native` (`v1.2.0`) on npm:
https://www.npmjs.com/package/@formbricks/react-native

pls upgrade and try again, it should work this time 🙏
if you still face issues, feel free to drop them here

**Comment by CesarNobre** [comment] 2024-12-07 05:40
it worked! thank you very much @pandeymangg @mattinannt!

**Closed** 2024-12-09 07:45 UTC

**Comment by Sarmadkhalid1** [comment] 2024-12-09 17:26
It worked for me also, Thanks for your quick response @pandeymangg
