### ISSUE TITLE
[BUG] Opening Survey Throws Run Time Error

### ISSUE THREAD

**Issue by piyushgarg-dev** [formbricks/formbricks#1377] opened 2023-10-21 09:14 UTC
### Issue Summary

If we try to open a old survey, it throws an error (Video Attached)an

### Steps to Reproduce

1. Go to the form bricks dashboard
2. Open Survey
3. You'll see the error

### Expected behavior

Survey Edit Mode must be opened without any error

### Screenshots

https://github.com/formbricks/formbricks/assets/44976328/1de8b453-5868-4424-9131-4848fafc0ff5

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by krishanu7** [comment] 2023-10-21 10:23
@piyushgarg-dev  are you trying bhaiya ? else i can try to resolve the issue

**Comment by ShubhamPalriwala** [comment] 2023-10-21 12:23
Hey @piyushgarg-dev, thanks a lot for opening the issue✨

However, I tried to reproduce the issue but was not able to! Will you be able to provide further details about the survey or anything that can help us debug?

PS: I know you cannot open the survey but any information would be really critical to us🚀

**Comment by piyushgarg-dev** [comment] 2023-10-21 12:40
Hi @ShubhamPalriwala, I just noticed that the form in the video is no longer on my dashboard. My assumption is that I deleted that form in the past and was somehow visible in the local state or cache.
Btw there is a link in the video, can we check if that form is in the deleted state or what?

Thanks 🙏🏻

**Comment by ShubhamPalriwala** [comment] 2023-10-23 12:41
Hey @piyushgarg-dev, since we were unable to replicate it and it got fixed for you as well (possibly a cache issue). I'm closing this for now. If anybody witnesses the same and ends up here, please feel free to open it 🙏🏼

**Closed by ShubhamPalriwala** 2023-10-23 12:41 UTC
Labels: bug
