### ISSUE TITLE
[BUG] Unable to see question preview for email protected surveys

### ISSUE THREAD

**Issue by ksushant6566** [formbricks/formbricks#2287] opened 2024-03-19 19:22 UTC
### Issue Summary

Question preview shows ```[Object object]``` when trying to view preview of email protected surveys

### Steps to Reproduce

1. go to [a survey](https://app.formbricks.com/s/clty2r3bm1bf512gsavwd2nib)
2. Click on ```preview survey questions```

### Expected behavior

Should show valid question preview

### Screenshots

https://www.loom.com/share/41a6b8c345f84815a9d75a69a0877d5f?sid=169fb72a-3e90-4e94-9a6c-f49218f562cf

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Macos  
- Node: N/a
- npm: N/a
```

**Comment by mattinannt** [comment] 2024-03-19 19:44
@ksushant6566 thanks for pointing this out :-) A fix for this issue is already in development and will be released soon 😊

**Comment by mattinannt** [comment] 2024-03-19 20:05
@ksushant6566 the issue is now fixed :-)

**Closed by mattinannt** 2024-03-19 20:05 UTC
Labels: bug
